name = "chrisboyd-telemetry"
main = "index.js"
compatibility_date = "2023-04-04"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install"

# Configure a custom domain for your worker (uncomment when ready)
# [routes]
# pattern = "chrisboyd-telemetry.kojikeneda.workers.dev/*"
# zone_name = "kojikeneda.workers.dev"

[vars]
# These will be set in the Cloudflare dashboard
# DASH0_API_KEY = ""
# DASH0_ENDPOINT = "https://ingress.us-west-2.aws.dash0.com:4317"
# DASH0_DATASET = "default"
# OTEL_SERVICE_NAME = "chrisboyd-blog" 