name = "chrisboyd-telemetry"
main = "index.js"
compatibility_date = "2024-04-04"
compatibility_flags = ["nodejs_compat"]

# Secrets (these should be set using wrangler secret):
# DASH0_API_KEY = ""
# DASH0_ENDPOINT = "https://ingress.us-west-2.aws.dash0.com:4317"
# DASH0_DATASET = "default" 
# AUTH_TOKEN = "" 