name = "chrisboyd-telemetry"
main = "src/index.js"
compatibility_date = "2024-04-03"

# Configure the worker to handle telemetry
[vars]
# You'll need to add these in the Cloudflare dashboard or via wrangler secret
# DASH0_API_KEY = ""
# DASH0_ENDPOINT = "https://ingress.us-west-2.aws.dash0.com:4317"
# DASH0_DATASET = "default"

# Configure routes (when deployed to Cloudflare)
# [routes]
# route = "telemetry.chrisboyd.dev/*"

# For local development
[dev]
port = 8089 